version: "3.8"

services:
  core:
    build:
      context: .
      dockerfile: ./apps/core/Dockerfile
    environment:
      MIX_ENV: prod
      SURREALDB_HOSTNAME: ${SURREALDB_HOSTNAME:-surrealdb}
      SURREALDB_PORT: ${SURREALDB_PORT:-8000}
      SURREALDB_USERNAME: ${SURREALDB_USERNAME:-root}
      SURREALDB_PASSWORD: ${SURREALDB_PASSWORD:-root}
      SURREALDB_DATABASE: ${SURREALDB_DATABASE:-xplore}
      SURREALDB_NAMESPACE: ${SURREALDB_NAMESPACE:-default}
      PORT: ${BACKEND_PORT:-4000}
    networks:
      - stack_network
    depends_on:
      - surrealdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://core:${BACKEND_PORT:-4000}"]
      interval: 10s

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT:-3000}
      BACKEND_URL: ${BACKEND_URL:-http://localhost:${STACK_PORT:-80}/api}
    networks:
      - stack_network
    depends_on:
      - core

  surrealdb:
    image: surrealdb/surrealdb:latest
    networks:
      - stack_network
    command: start --bind ${surrealdb:-0.0.0.0}:${SURREALDB_PORT:-8000} --log debug --user ${SURREALDB_USERNAME:-root} --pass ${SURREALDB_PASSWORD:-root} memory
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://surrealdb:${SURREALDB_PORT:-8000}/status"]
      interval: 10s

  nginx:
    image: nginx:latest
    ports:
      - "${STACK_PORT:-80}:80"
    volumes:
      - ./apps/proxy/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./apps/proxy/start-nginx.sh:/start-nginx.sh:ro
    networks:
      - stack_network
    cap_add:
      - CAP_NET_BIND_SERVICE
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-4000}
      FRONTEND_PORT: ${FRONTEND_PORT:-3000}
    entrypoint: /start-nginx.sh
    depends_on:
      - core
      - ui

networks:
  stack_network:
