import { faker } from "@faker-js/faker";
import type { Site } from "../src/@types/sites";

export const MOCK_GENERATOR = {
  Site: (partial: Partial<Site> = {}): Site => ({
    unique_number: faker.number.int(),
    id_no: faker.string.uuid(),
    rev_bis: faker.lorem.word(),
    name_en: faker.lorem.word(),
    name_fr: faker.lorem.word(),
    name_es: faker.lorem.word(),
    name_ru: faker.lorem.word(),
    name_ar: faker.lorem.word(),
    name_zh: faker.lorem.word(),
    short_description_en: faker.lorem.sentence(),
    short_description_fr: faker.lorem.sentence(),
    short_description_es: faker.lorem.sentence(),
    short_description_ru: faker.lorem.sentence(),
    short_description_ar: faker.lorem.sentence(),
    short_description_zh: faker.lorem.sentence(),
    justification_en: faker.lorem.sentence(),
    justification_fr: faker.lorem.sentence(),
    date_inscribed: faker.date.anytime().getTime(),
    secondary_dates: faker.date.anytime().toString(),
    danger: faker.number.int(),
    date_end: faker.date.anytime().toString(),
    danger_list: faker.lorem.word(),
    longitude: faker.number.float(),
    latitude: faker.number.float(),
    area_hectares: faker.number.float(),
    C1: faker.number.int(),
    C2: faker.number.int(),
    C3: faker.number.int(),
    C4: faker.number.int(),
    C5: faker.number.int(),
    C6: faker.number.int(),
    N7: faker.number.int(),
    N8: faker.number.int(),
    N9: faker.number.int(),
    N10: faker.number.int(),
    criteria_txt: faker.lorem.words(),
    category: faker.lorem.word(),
    category_short: faker.lorem.slug(),
    states_name_en: faker.lorem.word(),
    states_name_fr: faker.lorem.word(),
    states_name_es: faker.lorem.word(),
    states_name_ru: faker.lorem.word(),
    states_name_ar: faker.lorem.word(),
    states_name_zh: faker.lorem.word(),
    region_en: faker.lorem.word(),
    region_fr: faker.lorem.word(),
    iso_code: faker.number.octal().toString(),
    udnp_code: faker.number.octal().toString(),
    transboundary: faker.number.int(),
    id: faker.string.uuid(),
    ...partial,
  }),
};
