defmodule Xplore.Sites.Domain.WHCSite do
  use ExConstructor

  @type t :: %__MODULE__{
          unique_number: integer(),
          id_no: integer(),
          rev_bis: String.t() | binary(),
          name_en: String.t() | binary(),
          name_fr: String.t() | binary(),
          name_es: String.t() | binary(),
          name_ru: String.t() | binary(),
          name_ar: String.t() | binary(),
          name_zh: String.t() | binary(),
          short_description_en: String.t() | binary(),
          short_description_fr: String.t() | binary(),
          short_description_es: String.t() | binary(),
          short_description_ru: String.t() | binary(),
          short_description_ar: String.t() | binary(),
          short_description_zh: String.t() | binary(),
          justification_en: String.t() | binary(),
          justification_fr: String.t() | binary(),
          date_inscribed: integer(),
          secondary_dates: String.t() | binary(),
          danger: integer(),
          date_end: String.t() | binary(),
          danger_list: String.t() | binary(),
          longitude: float(),
          latitude: float(),
          area_hectares: integer(),
          C1: integer(),
          C2: integer(),
          C3: integer(),
          C4: integer(),
          C5: integer(),
          C6: integer(),
          N7: integer(),
          N8: integer(),
          N9: integer(),
          N10: integer(),
          criteria_txt: String.t() | binary(),
          category: String.t() | binary(),
          category_short: String.t() | binary(),
          states_name_en: String.t() | binary(),
          states_name_fr: String.t() | binary(),
          states_name_es: String.t() | binary(),
          states_name_ru: String.t() | binary(),
          states_name_ar: String.t() | binary(),
          states_name_zh: String.t() | binary(),
          region_en: String.t() | binary(),
          region_fr: String.t() | binary(),
          iso_code: String.t() | binary(),
          udnp_code: String.t() | binary(),
          transboundary: integer(),
          id: String.t() | binary()
        }

  defstruct [
    :name_es,
    :C3,
    :latitude,
    :region_fr,
    :danger,
    :short_description_es,
    :secondary_dates,
    :rev_bis,
    :id_no,
    :short_description_en,
    :udnp_code,
    :states_name_en,
    :criteria_txt,
    :justification_fr,
    :N8,
    :name_ar,
    :name_ru,
    :short_description_fr,
    :region_en,
    :date_inscribed,
    :date_end,
    :states_name_ar,
    :id,
    :name_en,
    :states_name_fr,
    :longitude,
    :N9,
    :transboundary,
    :states_name_ru,
    :justification_en,
    :unique_number,
    :short_description_ar,
    :area_hectares,
    :N10,
    :C5,
    :C4,
    :C1,
    :iso_code,
    :short_description_ru,
    :danger_list,
    :name_fr,
    :C6,
    :C2,
    :category_short,
    :category,
    :N7,
    :short_description_zh,
    :states_name_zh,
    :states_name_es,
    :name_zh
  ]
end
