name: Core CI

on:
  push:
    paths:
      - "apps/core/**"
  pull_request:
    paths:
      - "apps/core/**"

workflow_dispatch:

jobs:
  test-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/core
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.13"
          otp-version: "24"

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test

  build-core:
    runs-on: ubuntu-latest
    needs: test-core
    defaults:
      run:
        working-directory: apps/core
    steps:
      - name: Build application
        run: mix compile
